name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: "set up JDK 17"
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: "Get Branch Name"
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew

    - name: "Build Release"
      if: env.BRANCH == 'master' && github.event_name != 'pull_request'
      run: ./gradlew assembleRelease

    - name: "Build Debug"
      if: env.BRANCH != 'master' || github.event_name == 'pull_request'
      run: ./gradlew assembleDebug

    - name: "Get Short SHA"
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: "Get Version"
      run: echo "VERSION=$(echo $(cat app/build.gradle.kts | grep versionName | cut -d "=" -f 2 | sed "s/\"//g"))" >> $GITHUB_ENV
          
    - name: "Create Release"
      if: env.BRANCH == 'master' && github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v2
      with:
        name: "MiceWine Application (${{ env.VERSION }})"
        tag_name: ${{ env.SHORT_SHA }}
        prerelease: true
        files: ./app/build/outputs/apk/release/app-release.apk
    
    - name: "Upload Artifact"
      if: env.BRANCH != 'master' || github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: MiceWine-Application-(git-${{ env.SHORT_SHA }})
        path: ./app/build/outputs/apk/debug/app-debug.apk
